# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Joe Sankey"
description:

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/js_logo.png"
# blog cover
cover: "/assets/images/space.jpg"

name: 'Joe Sankey'
author: 'Joe Sankey'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://joesankey.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/joesankey
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/joesankey
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
